### ISSUE TITLE
how use it?

### ISSUE THREAD

**Issue by blogdron** [jordwalke/VimCompleteLikeAModernEditor#3]
i install jordwalke/AutoComplPop and jordwalke/VimCompleteLikeAModernEditor

1 - why this fork AutoComplPop use AcpDisable default?

i created my snippets in .vim/myUltiSnips/c.snippet 

snippet hellos
hellohello
endsnippet

i create main.c and write  hellos but i don`t see  popup list ((

what am I doing wrong?
P.S sorry for my English ::)

**Comment by jordwalke** [comment]
You can try https://github.com/jordwalke/VimBox to see it in action. I forked because the keyboard interaction didn't quite work well with UltiSnips and PairTools. Maybe I just didn't know how to use AutoComplPop effectively?

**Comment by jordwalke** [comment]
Perhaps this is a better solution - to use a fork that allows extensibility: https://github.com/eikenb/acp

**Comment by blogdron** [comment]
Thanks you ::)
